### ISSUE TITLE
MAS Monitor. When a new node is added, some existing nodes are no longer rendered

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#88]
I do quite a "heavy" page for MFD, rich graphics, and ran into a problem. At some point, after adding a new image or graphical node (such as Horizontal Bar), one or more existing nodes will no longer be rendered on the screen.

**Comment by MOARdV** [comment]
Do you know approximately how many nodes?

**Comment by Alexustas** [comment]
I know exactly )

28 IMAGES (2 of them do not rendered now)
1 VERTICAL_STRIP
4 HORIZONTAL_BAR (when I added 3rd and 4th, two images disappeared)
4 LINE_STRINGS
16 TEXT

**Comment by Alexustas** [comment]
sketch

![bandicam 2017-11-26 04-49-49-672](https://user-images.githubusercontent.com/6713671/33235892-5072b3ea-d265-11e7-894d-b873ada8db9d.jpg)

**Comment by MOARdV** [comment]
Make less complex MFD screens. :-)

Can you post the config for that page, so I can see if the order is important?

**Comment by Alexustas** [comment]
I was afraid, although I expected that you would say exactly this :-D 

config
https://www.dropbox.com/s/qx9g0inykuquri8/ASET_MFD2302_PFD_LANDING.cfg?dl=0

**Comment by Alexustas** [comment]
with the order of rendering layers there are also problems. it is difficult for me to explain this precisely, since I have not yet understood what exactly is happening, but it looks something like this. 
I compose, for example, such a config:

 background image fof text (1)
 text (1)
 background image fof text (2)
 text (2)
 background image fof text (#3)
 text (3)
...
 background image fof text (8)
 text (8)
image(1)
image(2)
...

and at some point, the text (2) turns out to be **below** the its background image (2), although initially it was rendered **over (or above)** its background image. (_number of nodes and the number of layers are listedroughly, for illustration_). So I came to the conclusion that the most reliable way is to put **all** images on the very bottom of the rendered scene (at the very top of the config)

**Comment by MOARdV** [comment]
This happens to me with a much simpler page, too.  There is something incorrect with the depth sorting, and I can change what text is visible or hidden by changing the order of the images.

**Comment by MOARdV** [comment]
Fixed on [DropBox](https://www.dropbox.com/s/3j0k2q5hesb84bq/AvionicsSystems-0.11.0b2.zip?dl=0) - I was changing image depth twice when I allowed the image position to change.

Also changed glide slope sector size and turned around glide slope beacons.

**Comment by Alexustas** [comment]
There is still a problem with the depth sorting.

I have the following config:

```
MAS_PAGE
{
	name =  ASET_MFD2302_MFD_FONTS_TEST
	
	
	IMAGE
	{
		name = BKG
		position = 640, 64
		size = 128, 448
		texture = ASET/ASET_Props_MAS/ASET_MAS_MFD/Common_Images/ScreenWarningWHITE
		passiveColor = 70, 70, 70, 255		
	}
	
	TEXT
	{
		name = TAPE
		position = 40, 2
		textColor = 51, 102, 153, 255
		text = <=0=> $&$ ASET_DigitalTapeGenerator(fc.Altitude(),7,200,64,true,8,"[#FFFFFF]","[#FFFF00]",1000)
	}
	
	VIEWPORT
	{
		name = Test Viewport
			
		upperLeftCorner = 640, 64
		lowerRightCorner = 768, 512
			
		color = 0, 0, 0, 255
			
		//variable =
		//range =
	}
	
	
	IMAGE
	{
		name = black plate
		position = 656, 256
		texture = ASET/ASET_Props_MAS/ASET_MAS_MFD/Common_Images/TapeReadoutPlate		
	}
	
	TEXT
	{
		name = readout
		position = 40, 8
		textColor = 255, 255, 255, 255
		text = <=0,8:###000=> $&$fc.Altitude()
	}
	
	TEXT
	{
		name = TAPE copy
		position = 25, 2
		textColor = 51, 102, 153, 255
		text = <=0=> $&$ ASET_DigitalTapeGenerator(fc.Altitude(),7,200,64,true,8,"[#FFFFFF]","[#FFFF00]",1000)
	}
}
```

how it looks in the game:
https://youtu.be/ir7BT9QGzTI

as you can see, the black plate under the Altitude readings are cropped to the right and this means that the VIEWPORT nide rendered above this plate, although in the config it is specified before black plate

**Comment by MOARdV** [comment]
Fixed on [DropBox](https://www.dropbox.com/s/3j0k2q5hesb84bq/AvionicsSystems-0.11.0b2.zip?dl=0).  I found the same bug with NAVBALL yesterday.  I will check again to make sure I fixed all of them.

**Comment by Alexustas** [comment]
> Fixed 

Yes, thank you!

![bandicam 2017-12-02 00-44-42-203](https://user-images.githubusercontent.com/6713671/33500306-309ce204-d6fa-11e7-9084-7e1e885fcddd.jpg)
